Examples: require to require_once; PHP 5 to 7
CpuID/pve2-api-php-client pull request #38
Opened 2022-02-17 07:58 UTC by lsthompson

Seems happy on PHP7, though we've implemented the class for PMG not PVE. Updated examples from require to require_once.

2022-02-27 05:54 UTC, lsthompson commented
Hey, is this okay to merge?

2022-03-10 03:45 UTC, danhunsaker requested changes

2022-03-10 03:45 UTC, danhunsaker commented on README.md
> +        print_r($pve2->post("/nodes/".$first_node."/openvz",$new_container_settings));
Should probably leave the space here.

2022-03-10 03:45 UTC, danhunsaker commented on README.md
> +        var_dump($pve2->put("/nodes/".$first_node."/openvz/XXXX/config",$container_settings));
Same as above, leave the space.

2022-03-10 03:45 UTC, danhunsaker commented on README.md
> +PHP 7 with cURL (including SSL/TLS) support.
Does this no longer work on 5.x? I'd feel better saying "5 or higher" if it isn't actually broken there. I know 5 is massively outdated, but I'm sure it's still in the wild somewhere.

2022-03-10 03:52 UTC, lsthompson reviewed
Good pick-ups @danhunsaker. Now tweaked - thanks.

2022-03-10 04:06 UTC, danhunsaker approved these changes

2022-03-10 04:07 UTC, merged